Make docs build only if source files changes

diff --git a/.readthedocs.yml b/.readthedocs.yml
--- a/.readthedocs.yml
+++ b/.readthedocs.yml
@@ -11,6 +11,17 @@ build:
   tools:
     python: "3.10"
   jobs:
+    post_checkout:
+      # Cancel building pull requests when there aren't changes in the docs directory, keras_mml 
+      # directory, or readthedocs YAML file.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ keras_mml/ .readthedocs.yml;
+        then
+          exit 183;
+        fi
     post_create_environment:
       # Install poetry
       # https://python-poetry.org/docs/#installing-manually
